#!/bin/sh

mkdir -p opk/

cd /opt/picoarch
./package
cp picoarch README.funkey-s.md ../libretro-vitaquake2/opk

cd /opt/libretro-vitaquake2
git fetch --all
git merge upstream/libretro
git submodule update --remote --recursive
make clean
make
/opt/FunKey-sdk/bin/arm-funkey-linux-musleabihf-strip *.so
cp vitaquake2_libretro.so opk/

cp icons/quake2.png opk/
cp LICENSE opk/

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GMenu2X entry file plus other things

print '[Desktop Entry]
Name=Quake II
Comment=VitaQuake 2 v2.3 for Libretro
Exec=picoarch ./vitaquake2_libretro.so
Icon=quake2
Categories=games' > opk/vitaquake2.funkey-s.desktop

rm -f *.opk
mksquashfs opk/ vitaquake2_v2.3_funkey-s.opk -all-root -noappend -no-exports -no-xattrs

rm -rf opk/
