#!/bin/sh

mkdir -p opk/cores

cd /opt/sdlretro
git pull
mkdir -p build/
cd build/
cmake -DCMAKE_BUILD_TYPE=Release -DMODEL=funkey ..
make clean
make
/opt/FunKey-sdk/bin/arm-funkey-linux-musleabihf-strip src/sdlretro
cp src/sdlretro ../../libretro-vitaquake2/opk

cd /opt/libretro-vitaquake2
git fetch --all
git merge upstream/libretro
make clean
make
/opt/FunKey-sdk/bin/arm-funkey-linux-musleabihf-strip *.so
cp vitaquake2_libretro.so opk/cores/

cp icons/quake2.png opk/
cp LICENSE opk/

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GMenu2X entry file plus other things

print '[Desktop Entry]
Name=Quake II
Comment=VitaQuake 2 v2.3 for Libretro
Exec=sdlretro %f
Icon=quake2
Categories=games
SelectorFilter=pak' > opk/quake2.funkey-s.desktop

rm -f *.opk
mksquashfs opk/ vitaquake2_v2.3_funkey-s.opk -all-root -noappend -no-exports -no-xattrs

rm -rf opk/
